import type { ChatKitOptions } from "@openai/chatkit";

const options: ChatKitOptions = {
  api: {
    // TODO: configure your ChatKit API integration (URL, auth, uploads).
  },

  // THEME FROM PLAYGROUND (custom colors)
  theme: {
    colorScheme: 'light',
    radius: 'pill',
    density: 'spacious',
    color: {
      grayscale: {
        hue: 140,
        tint: 7,
        shade: 1
      },
      accent: {
        primary: '#1b5f1c',
        level: 1
      }
    },
    typography: {
      baseSize: 16,
      fontFamily: '"OpenAI Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", sans-serif',
      fontFamilyMono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "DejaVu Sans Mono", "Courier New", monospace',
      fontSources: [
        {
          family: 'OpenAI Sans',
          src: 'https://cdn.openai.com/common/fonts/openai-sans/v2/OpenAISans-Regular.woff2',
          weight: 400,
          style: 'normal',
          display: 'swap'
        }
      ]
    },

    // 👉 IMPORTANT: Hide header/title generated by ChatKit
    header: {
      visible: false,
    },
  },

  // COMPOSER (input area)
  composer: {
    placeholder: ' ',
    attachments: {
      enabled: false
    },
    tools: [
      {
        id: 'create_theme',
        label: 'Create theme',
        shortLabel: 'Theme',
        placeholderOverride: 'Describe your chat application',
        icon: 'sparkle-double',
        pinned: false
      }
    ],
  },

  // START SCREEN
  startScreen: {
    greeting: ' ',  // empty greeting (you can put your own)
    prompts: [],     // REMOVE “What can you do?” etc
  },

  // 👉 IMPORTANT: Also disable top header completely
  header: false,
};

export default options;
